
title: "Documentation Projet Cofolio"
description: "Suivi des projets Cofolio et développement — équipe remote"
theme: minima
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuration Pages
baseurl: ""  # laisser vide pour un dépôt user, sinon "/nom-du-repo"
url: "https://jgribonvald.github.io"
permalink: /:path/

# Exclusions (inutile de publier ça)
exclude:
  - .github/
  - .gitignore
  - README.md
  - "*.tar.gz"
  - tmp/

# Déploiement GitHub Pages
github:
  is_project_page: true
