
title: "Documentation Projet Cofolio"
description: "Suivi des projets Cofolio et développement — équipe remote"
theme: minima
baseurl: ""
markdown: kramdown

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"

nav:
  - title: "Accueil"
    url: "/"
  - title: "Guide Projet"
    url: "/docs/guide-projet"
  - title: "Wiki"
    url: "https://github.com/jgribonvald/example-gestion-projet/wiki"
  - title: "GitHub Project"
    url: "https://github.com/orgs/jgribonvald/projects/1"
  - title: "Nextcloud"
    url: "https://nextcloud.recia.fr.fr"
